### ISSUE TITLE
Бот

### ISSUE THREAD

**Issue by webistomin** [insulineru/fixmoney#1]
А где исходники бота?😀

**Comment by insulineru** [comment]
![image](https://user-images.githubusercontent.com/20267733/100716204-6de37b80-33c9-11eb-9f18-e3b6d13355bb.png)
Сейчас вот в таком виде исходники, буду переписывать на node и telegraf плюс свой бекэнд делать, но к январю. Тогда уже буду думать о публикации исходников 😉

**Comment by webistomin** [comment]
Пили статью в TJ😁
